export  interface IOffrecondidat
{
   id?:number,
   datecreation?:Date
   nom?:string,
   prenom?:string,
   poste?:string,
   cin?:string,
  dateOfBirth:Date,
  phone:string,
  adresse:string,
  ville:string,
  nationality:string,
  niveauEtud:string,
  titreDiplome:string,
  university:string,
  niveauExp:string,
  titredoffre?:string,
  description?:string,
  datelimite?:Date,
  langue?:string,
  experience?:string,
  exigenceemploie:string,
  status?:string
  hasinterview:boolean;
}
